"""
ARCADE MCP Server
Auto-generated by setup.sh — edit mcp-server.conf to change configuration.
Run with: ./start.sh
"""
import os
from mcp.server.fastmcp import FastMCP
from arcade_tools import register_arcade_tools


def load_conf():
    conf_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mcp-server.conf")
    if os.path.exists(conf_path):
        with open(conf_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    k = k.strip()
                    v = v.strip().strip('"').strip("'")
                    os.environ.setdefault(k, v)


load_conf()

mcp = FastMCP("arcade")
register_arcade_tools(mcp)

if __name__ == "__main__":
    mcp.run()
